// <auto-generated />
namespace EventManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newUpdate29082019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newUpdate29082019));
        
        string IMigrationMetadata.Id
        {
            get { return "201908290625381_newUpdate29-08-2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
